import { IconRegistry } from '@tylertech/forge';
import {
  tylIconArrowBack,
  tylIconDashboard,
  tylIconPerson,
  tylIconListAlt,
  tylIconPets,
  tylIconChildFriendly,
  tylIconHome,
  tylIconMenu,
  tylIconSearch,
  tylIconCategory,
  tylIconFilterList,
  tylIconDelete,
  tylIconAdd,
  tylIconAddCircle,
  tylIconArrowDropDown,
  tylIconEdit,
  tylIconContentCopy,
  tylIconBolt,
  tylIconCheck,
  tylIconViewColumn,
  tylIconChevronLeft,
  tylIconChevronRight,
  tylIconClose,
  tylIconMap,
  tylIcon360,
  tylIconExpandLess,
  tylIconExpandMore,
  tylIconKeyboardArrowRight,
  tylIconDirections,
  tylIconStar,
  tylIconError,
  tylIconMoreVert
} from '@tylertech/tyler-icons/standard';

const standardIcons = [
  tylIconArrowBack,
  tylIconDashboard,
  tylIconPerson,
  tylIconListAlt,
  tylIconPets,
  tylIconChildFriendly,
  tylIconHome,
  tylIconMenu,
  tylIconSearch,
  tylIconCategory,
  tylIconFilterList,
  tylIconDelete,
  tylIconAdd,
  tylIconAddCircle,
  tylIconArrowDropDown,
  tylIconEdit,
  tylIconContentCopy,
  tylIconBolt,
  tylIconCheck,
  tylIconViewColumn,
  tylIconChevronLeft,
  tylIconChevronRight,
  tylIconClose,
  tylIconMap,
  tylIcon360,
  tylIconExpandLess,
  tylIconExpandMore,
  tylIconKeyboardArrowRight,
  tylIconDirections,
  tylIconStar,
  tylIconError,
  tylIconMoreVert
];

export const defineIcons = () => {
  IconRegistry.define(standardIcons);
};